version: '3'

services:
  cep-weather-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
